project:
  type: website

website:
  title: "PADME"
  navbar:
    right:
      - href: index.qmd
        text: Forskning
      - team.md
      - text: Projects
        menu:
          - projects/prepare-child.md
          - projects/ppc.md

format:
  html:
    theme:
      - flatly
      - theme.scss
    toc: true

editor: visual
