project:
  type: website

website:
  title: "PADME"
  navbar:
    right:
      - href: index.qmd
        text: Forskning
      - about.qmd
      - text: Projekter
        menu:
          - projects/prepare-child.md
          - projects/ppc.md
      - text: Kontakt
        href: kontakt.md




format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

